# Generated by Django 6.0.5 on 2026-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_stock_quantity_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
